# Generated by Django 2.2.7 on 2019-12-02 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='phone_book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_name', models.CharField(default='', max_length=250)),
                ('phone_number', models.CharField(default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('created_by', models.CharField(default='', max_length=7)),
                ('address', models.TextField()),
                ('age', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UsersAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=250)),
                ('password', models.CharField(default='', max_length=250)),
            ],
        ),
    ]
