# Generated by Django 3.0 on 2019-12-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191203_1744'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AddField(
            model_name='user',
            name='Country',
            field=models.CharField(choices=[('Cairo', 'Cairo'), ('Alex', 'Alex'), ('DK', 'Dakahlia'), ('BA', 'Banha')], default='Cairo', max_length=5),
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='company_site',
            field=models.URLField(blank=True),
        ),
    ]
