# Generated by Django 3.0 on 2019-12-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarcTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MarcTemplateTitle', models.CharField(max_length=200)),
                ('biblio_type_id', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=200)),
                ('jsonObject', models.TextField()),
            ],
        ),
    ]
